-- CreateEnum
CREATE TYPE "TipoUsuario" AS ENUM ('INTERNO', 'EXTERNO');

-- CreateEnum
CREATE TYPE "NivelUsuario" AS ENUM ('USUARIO', 'ADMINISTRADOR');

-- CreateEnum
CREATE TYPE "CategoriaUsuarioExterno" AS ENUM ('ESTUDIANTE', 'EGRESADO', 'EMPRESA');

-- CreateEnum
CREATE TYPE "TipoPerfilTalento" AS ENUM ('ESTUDIANTE', 'EGRESADO', 'EMPRENDEDOR');

-- CreateEnum
CREATE TYPE "AreaTalento" AS ENUM ('MUSICA', 'ARTES_PLASTICAS', 'DISENO', 'AUDIOVISUAL', 'ARTES_ESCENICAS');

-- CreateEnum
CREATE TYPE "AreaCreativaEmprendimiento" AS ENUM ('ARTES_PLASTICAS', 'MUSICA', 'DISENO', 'AUDIOVISUAL');

-- CreateEnum
CREATE TYPE "EstadoLaboralEgresado" AS ENUM ('EMPLEADO', 'EMPRENDEDOR', 'DESEMPLEADO', 'ESTUDIANDO');

-- CreateEnum
CREATE TYPE "TipoConvocatoriaEmprendimiento" AS ENUM ('FINANCIAMIENTO', 'FORMACION', 'PRACTICAS');

-- CreateEnum
CREATE TYPE "EstadoPostulacionConvocatoria" AS ENUM ('POSTULADO', 'RECHAZADO', 'APROBADO');

-- CreateEnum
CREATE TYPE "EstadoPropuestaFeria" AS ENUM ('POSTULADO', 'RECHAZADO', 'ACEPTADO');

-- CreateTable
CREATE TABLE "USUARIOS" (
    "IDUSUARIO" SERIAL NOT NULL,
    "USUARIO" TEXT NOT NULL,
    "DESCRIPCION" TEXT,
    "CLAVE" TEXT NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "NIVEL" "NivelUsuario" NOT NULL,
    "TIPO" "TipoUsuario" NOT NULL,
    "CORREO" TEXT,
    "CELULAR" TEXT,
    "ID_ROL" INTEGER,
    "CATEGORIA_EXTERNA" "CategoriaUsuarioExterno",

    CONSTRAINT "USUARIOS_pkey" PRIMARY KEY ("IDUSUARIO")
);

-- CreateTable
CREATE TABLE "ROLES" (
    "ID_ROL" SERIAL NOT NULL,
    "CODIGO" TEXT NOT NULL,
    "NOMBRE" TEXT NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "ROLES_pkey" PRIMARY KEY ("ID_ROL")
);

-- CreateTable
CREATE TABLE "ROLES_PERMISOS" (
    "ID_ROL_PERMISO" SERIAL NOT NULL,
    "ID_ROL" INTEGER NOT NULL,
    "IDMODULO" INTEGER NOT NULL,
    "IDACCION" INTEGER NOT NULL,

    CONSTRAINT "ROLES_PERMISOS_pkey" PRIMARY KEY ("ID_ROL_PERMISO")
);

-- CreateTable
CREATE TABLE "ESTUDIANTES_HABILITADOS" (
    "ID" SERIAL NOT NULL,
    "IDENTIFICACION" TEXT NOT NULL,
    "CODIGO_ESTUDIANTIL" TEXT NOT NULL,
    "NOMBRES" TEXT NOT NULL,
    "APELLIDOS" TEXT NOT NULL,
    "PROGRAMA" VARCHAR(200),
    "SEMESTRE" INTEGER,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ESTUDIANTES_HABILITADOS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "EGRESADOS_HABILITADOS" (
    "ID" SERIAL NOT NULL,
    "IDENTIFICACION" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EGRESADOS_HABILITADOS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "EMPRESAS" (
    "ID" SERIAL NOT NULL,
    "ID_USUARIO" INTEGER NOT NULL,
    "NIT" TEXT NOT NULL,
    "RAZON_SOCIAL" VARCHAR(300) NOT NULL,
    "NOMBRE_CONTACTO" VARCHAR(200),
    "CORREO_CONTACTO" TEXT,
    "TELEFONO" TEXT,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EMPRESAS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "EGRESADOS" (
    "ID" SERIAL NOT NULL,
    "IDUSUARIO" INTEGER NOT NULL,
    "NOMBRE_COMPLETO" TEXT NOT NULL,
    "IDENTIFICACION" TEXT NOT NULL,
    "TELEFONO" TEXT,
    "CORREO" TEXT NOT NULL,
    "ANIO_EGRESO" INTEGER NOT NULL,
    "PROGRAMA_CARRERA" VARCHAR(200) NOT NULL,
    "ESTADO_LABORAL" "EstadoLaboralEgresado" NOT NULL,
    "BREVE_PERFIL" TEXT NOT NULL,
    "INFO_EMPRENDIMIENTO" TEXT,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EGRESADOS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "TALENTO_PERFILES" (
    "ID" SERIAL NOT NULL,
    "IDUSUARIO" INTEGER NOT NULL,
    "NOMBRE_COMPLETO" TEXT NOT NULL,
    "AREA" "AreaTalento" NOT NULL,
    "HABILIDADES" TEXT NOT NULL,
    "PORTAFOLIO_URL" TEXT,
    "TELEFONO" TEXT,
    "CORREO_CONTACTO" TEXT,
    "PERFIL_ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "TIPO_PERFIL" "TipoPerfilTalento" NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TALENTO_PERFILES_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "EMPRENDIMIENTOS_DIRECTORIO" (
    "ID" SERIAL NOT NULL,
    "IDUSUARIO" INTEGER NOT NULL,
    "NOMBRE_PROYECTO" TEXT NOT NULL,
    "DESCRIPCION_CORTA" VARCHAR(500) NOT NULL,
    "IMAGEN_URL" TEXT,
    "CORREO" TEXT,
    "REDES" TEXT,
    "SITIO_WEB" TEXT,
    "AREA_CREATIVA" "AreaCreativaEmprendimiento" NOT NULL,
    "PERFIL_ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EMPRENDIMIENTOS_DIRECTORIO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "PUBLICACION_EMPRENDIMIENTO" (
    "ID" SERIAL NOT NULL,
    "TITULO" TEXT NOT NULL,
    "DESCRIPCION" TEXT NOT NULL,
    "TIPO_CONVOCATORIA" "TipoConvocatoriaEmprendimiento" NOT NULL,
    "CONVOCADOS" TEXT NOT NULL,
    "FECHA_LIMITE" TIMESTAMP(3) NOT NULL,
    "MONTO_TIPO_APOYO" TEXT,
    "LINK_EXTERNO" TEXT,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PUBLICACION_EMPRENDIMIENTO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "POSTULADOS_CONVOCATORIAS" (
    "ID" SERIAL NOT NULL,
    "ID_ESTUDIANTE" INTEGER NOT NULL,
    "ID_CONVOCATORIA" INTEGER NOT NULL,
    "FECHA_POSTULACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ESTADO_POSTULACION" "EstadoPostulacionConvocatoria" NOT NULL DEFAULT 'POSTULADO',

    CONSTRAINT "POSTULADOS_CONVOCATORIAS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "FERIAS" (
    "ID" SERIAL NOT NULL,
    "NOMBRE" TEXT NOT NULL,
    "DESCRIPCION" TEXT NOT NULL,
    "FECHA_INICIO" TIMESTAMP(3) NOT NULL,
    "FECHA_FIN" TIMESTAMP(3) NOT NULL,
    "IMAGEN_BANNER_URL" TEXT,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FERIAS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "FERIAS_PROPUESTAS" (
    "ID" SERIAL NOT NULL,
    "ID_USUARIO" INTEGER NOT NULL,
    "ID_FERIA" INTEGER NOT NULL,
    "NOMBRE_EMPRENDIMIENTO" TEXT NOT NULL,
    "DESCRIPCION_CORTA" VARCHAR(500) NOT NULL,
    "IMAGEN_URL" TEXT,
    "AREA_CREATIVA" "AreaCreativaEmprendimiento" NOT NULL,
    "REDES_CONTACTO" TEXT,
    "CORREO" TEXT NOT NULL,
    "CELULAR" TEXT,
    "ESTADO" "EstadoPropuestaFeria" NOT NULL DEFAULT 'POSTULADO',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FERIAS_PROPUESTAS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "MODULOS" (
    "IDMODULO" SERIAL NOT NULL,
    "NOMBRE" TEXT NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "MODULOS_pkey" PRIMARY KEY ("IDMODULO")
);

-- CreateTable
CREATE TABLE "ACCIONES" (
    "IDACCION" SERIAL NOT NULL,
    "NOMBRE" TEXT NOT NULL,

    CONSTRAINT "ACCIONES_pkey" PRIMARY KEY ("IDACCION")
);

-- CreateIndex
CREATE UNIQUE INDEX "USUARIOS_USUARIO_key" ON "USUARIOS"("USUARIO");

-- CreateIndex
CREATE INDEX "USUARIOS_ID_ROL_idx" ON "USUARIOS"("ID_ROL");

-- CreateIndex
CREATE UNIQUE INDEX "ROLES_CODIGO_key" ON "ROLES"("CODIGO");

-- CreateIndex
CREATE UNIQUE INDEX "ROLES_PERMISOS_ID_ROL_IDMODULO_IDACCION_key" ON "ROLES_PERMISOS"("ID_ROL", "IDMODULO", "IDACCION");

-- CreateIndex
CREATE INDEX "ESTUDIANTES_HABILITADOS_IDENTIFICACION_idx" ON "ESTUDIANTES_HABILITADOS"("IDENTIFICACION");

-- CreateIndex
CREATE UNIQUE INDEX "ESTUDIANTES_HABILITADOS_IDENTIFICACION_CODIGO_ESTUDIANTIL_key" ON "ESTUDIANTES_HABILITADOS"("IDENTIFICACION", "CODIGO_ESTUDIANTIL");

-- CreateIndex
CREATE UNIQUE INDEX "EGRESADOS_HABILITADOS_IDENTIFICACION_key" ON "EGRESADOS_HABILITADOS"("IDENTIFICACION");

-- CreateIndex
CREATE UNIQUE INDEX "EMPRESAS_ID_USUARIO_key" ON "EMPRESAS"("ID_USUARIO");

-- CreateIndex
CREATE UNIQUE INDEX "EMPRESAS_NIT_key" ON "EMPRESAS"("NIT");

-- CreateIndex
CREATE UNIQUE INDEX "EGRESADOS_IDUSUARIO_key" ON "EGRESADOS"("IDUSUARIO");

-- CreateIndex
CREATE UNIQUE INDEX "EGRESADOS_IDENTIFICACION_key" ON "EGRESADOS"("IDENTIFICACION");

-- CreateIndex
CREATE UNIQUE INDEX "EGRESADOS_CORREO_key" ON "EGRESADOS"("CORREO");

-- CreateIndex
CREATE INDEX "EGRESADOS_ANIO_EGRESO_idx" ON "EGRESADOS"("ANIO_EGRESO");

-- CreateIndex
CREATE INDEX "EGRESADOS_PROGRAMA_CARRERA_idx" ON "EGRESADOS"("PROGRAMA_CARRERA");

-- CreateIndex
CREATE INDEX "EGRESADOS_ESTADO_LABORAL_idx" ON "EGRESADOS"("ESTADO_LABORAL");

-- CreateIndex
CREATE UNIQUE INDEX "TALENTO_PERFILES_IDUSUARIO_key" ON "TALENTO_PERFILES"("IDUSUARIO");

-- CreateIndex
CREATE UNIQUE INDEX "EMPRENDIMIENTOS_DIRECTORIO_IDUSUARIO_key" ON "EMPRENDIMIENTOS_DIRECTORIO"("IDUSUARIO");

-- CreateIndex
CREATE INDEX "PUBLICACION_EMPRENDIMIENTO_TIPO_CONVOCATORIA_idx" ON "PUBLICACION_EMPRENDIMIENTO"("TIPO_CONVOCATORIA");

-- CreateIndex
CREATE INDEX "PUBLICACION_EMPRENDIMIENTO_ACTIVO_idx" ON "PUBLICACION_EMPRENDIMIENTO"("ACTIVO");

-- CreateIndex
CREATE INDEX "PUBLICACION_EMPRENDIMIENTO_FECHA_LIMITE_idx" ON "PUBLICACION_EMPRENDIMIENTO"("FECHA_LIMITE");

-- CreateIndex
CREATE UNIQUE INDEX "POSTULADOS_CONVOCATORIAS_ID_ESTUDIANTE_ID_CONVOCATORIA_key" ON "POSTULADOS_CONVOCATORIAS"("ID_ESTUDIANTE", "ID_CONVOCATORIA");

-- CreateIndex
CREATE INDEX "FERIAS_FECHA_INICIO_idx" ON "FERIAS"("FECHA_INICIO");

-- CreateIndex
CREATE INDEX "FERIAS_FECHA_FIN_idx" ON "FERIAS"("FECHA_FIN");

-- CreateIndex
CREATE INDEX "FERIAS_PROPUESTAS_ID_FERIA_ESTADO_idx" ON "FERIAS_PROPUESTAS"("ID_FERIA", "ESTADO");

-- CreateIndex
CREATE INDEX "FERIAS_PROPUESTAS_ID_USUARIO_idx" ON "FERIAS_PROPUESTAS"("ID_USUARIO");

-- CreateIndex
CREATE UNIQUE INDEX "FERIAS_PROPUESTAS_ID_USUARIO_ID_FERIA_key" ON "FERIAS_PROPUESTAS"("ID_USUARIO", "ID_FERIA");

-- CreateIndex
CREATE UNIQUE INDEX "MODULOS_NOMBRE_key" ON "MODULOS"("NOMBRE");

-- CreateIndex
CREATE UNIQUE INDEX "ACCIONES_NOMBRE_key" ON "ACCIONES"("NOMBRE");

-- AddForeignKey
ALTER TABLE "USUARIOS" ADD CONSTRAINT "USUARIOS_ID_ROL_fkey" FOREIGN KEY ("ID_ROL") REFERENCES "ROLES"("ID_ROL") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROLES_PERMISOS" ADD CONSTRAINT "ROLES_PERMISOS_ID_ROL_fkey" FOREIGN KEY ("ID_ROL") REFERENCES "ROLES"("ID_ROL") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROLES_PERMISOS" ADD CONSTRAINT "ROLES_PERMISOS_IDMODULO_fkey" FOREIGN KEY ("IDMODULO") REFERENCES "MODULOS"("IDMODULO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROLES_PERMISOS" ADD CONSTRAINT "ROLES_PERMISOS_IDACCION_fkey" FOREIGN KEY ("IDACCION") REFERENCES "ACCIONES"("IDACCION") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPRESAS" ADD CONSTRAINT "EMPRESAS_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIOS"("IDUSUARIO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EGRESADOS" ADD CONSTRAINT "EGRESADOS_IDUSUARIO_fkey" FOREIGN KEY ("IDUSUARIO") REFERENCES "USUARIOS"("IDUSUARIO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TALENTO_PERFILES" ADD CONSTRAINT "TALENTO_PERFILES_IDUSUARIO_fkey" FOREIGN KEY ("IDUSUARIO") REFERENCES "USUARIOS"("IDUSUARIO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPRENDIMIENTOS_DIRECTORIO" ADD CONSTRAINT "EMPRENDIMIENTOS_DIRECTORIO_IDUSUARIO_fkey" FOREIGN KEY ("IDUSUARIO") REFERENCES "USUARIOS"("IDUSUARIO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "POSTULADOS_CONVOCATORIAS" ADD CONSTRAINT "POSTULADOS_CONVOCATORIAS_ID_ESTUDIANTE_fkey" FOREIGN KEY ("ID_ESTUDIANTE") REFERENCES "USUARIOS"("IDUSUARIO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "POSTULADOS_CONVOCATORIAS" ADD CONSTRAINT "POSTULADOS_CONVOCATORIAS_ID_CONVOCATORIA_fkey" FOREIGN KEY ("ID_CONVOCATORIA") REFERENCES "PUBLICACION_EMPRENDIMIENTO"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FERIAS_PROPUESTAS" ADD CONSTRAINT "FERIAS_PROPUESTAS_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIOS"("IDUSUARIO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FERIAS_PROPUESTAS" ADD CONSTRAINT "FERIAS_PROPUESTAS_ID_FERIA_fkey" FOREIGN KEY ("ID_FERIA") REFERENCES "FERIAS"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
