/** Códigos de `ROLES.CODIGO` (RBAC). */
export const ROL_INTERNO_BASE = "INTERNO_BASE";
export const ROL_EXTERNO_ESTUDIANTE = "EXTERNO_ESTUDIANTE";
export const ROL_EXTERNO_EGRESADO = "EXTERNO_EGRESADO";
export const ROL_EXTERNO_EMPRESA = "EXTERNO_EMPRESA";
